name: puupee_api_client
version: 1.0.0
description: Api for puupee app service.
homepage: https://github.com/puupee/puupee-api-dart


environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  dio: '^5.7.0'
  json_annotation: '^4.9.0'

dev_dependencies:
  build_runner: any
  json_serializable: '^6.9.3'
  test: '^1.16.0'
